<?php

/* Author: Philipp Kapfer */

$labels = array();
$labels['purge'] = 'Ordnerbereinigung';
$labels['purgetrashfolder'] = 'Nachrichten im Papierkorb behalten für';
$labels['purgejunkfolder'] = 'Nachrichten im Spamordner behalten für';
$labels['purgealways'] = 'immer';
$labels['purgeday'] = 'Tag';
$labels['purgedays'] = 'Tage';

$messages = array();
$messages['purgesuccessfullysaved'] = 'Daten erfolgreich gespeichert';
$messages['purgedriverconnecterror'] = 'Fehler bei Treiberverbindung';
$messages['purgedriverprocesserror'] = 'Fehler bei Treiberausführung';
$messages['purgeinternalerror'] = 'Fehler beim Lesen des Treibers';

?>
