<?php

/* Author: Gianluca Giacometti */

$labels = array();
$labels['purge'] = 'purge';
$labels['purgetrashfolder'] = 'Keep messages in Trash folder for';
$labels['purgejunkfolder'] = 'Keep messages in Junk folder for';
$labels['purgealways'] = 'ever';
$labels['purgeday'] = 'day';
$labels['purgedays'] = 'days';

$messages = array();
$messages['purgesuccessfullysaved'] = 'Data successfully saved';
$messages['purgedriverconnecterror'] = 'Driver connection error';
$messages['purgedriverprocesserror'] = 'Driver execution error';
$messages['purgeinternalerror'] = 'Driver reading error';

?>
