<?php

/* Author: Gianluca Giacometti */

$labels = array();
$labels['purge'] = 'Pulizia cartelle';
$labels['purgetrashfolder'] = 'Mantieni i messaggi nel Cestino per';
$labels['purgejunkfolder'] = 'Mantieni i messaggi nella Posta indesiderata per';
$labels['purgealways'] = 'sempre';
$labels['purgeday'] = 'giorno';
$labels['purgedays'] = 'giorni';

$messages = array();
$messages['purgesuccessfullysaved'] = 'Dati salvati con successo';
$messages['purgedriverconnecterror'] = 'Errore di connessione del driver';
$messages['purgedriverprocesserror'] = 'Errore di esecuzione del driver';
$messages['purgeinternalerror'] = 'Errore di lettura del driver';

?>
